# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://github.com/huezo
# Victor H. <huezohuezo.1990@gmail.com>
# Victor H. <huezohuezo.1990@gmail.com>

trigger:
- master

pool:
  name: Default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: DevOps
  displayName: Docker image
  jobs:
  - job: DevOps
    displayName: DevOps
#    pool:
#      vmImage: ubuntu-latest
#    pool:
#      name: Default
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: 'build'
#        Dockerfile: '**/Dockerfile'
#        tags: '$(tag)'


    - task: Bash@3
      displayName: DevOps
      inputs:
        targetType: 'inline'
        script: |
          # Docker DevOps
          docker build --no-cache --tag libreclinica:master .
          docker rm -f libreclinica
          docker run -d --name libreclinica -p 8183:8080 libreclinica:master
          docker ps --filter name=libreclinica
          echo 'Hello DevOps'
          ls -ltra
        #  docker service rm libreclinica
        #  docker service create --name=libreclinica --restart-condition=any --publish=8183:8080 --hostname=localhost libreclinica:master
        #  docker service ps  libreclinica
           
    - task: Bash@3
      displayName: Test
      inputs:
        targetType: 'inline'
        script: |
          # 
          git clone https://github.com/Alagant/libreclinica-qa.git
          ls -ltra
          ls -ltra libreclinica-qa/
          docker-compose  -f libreclinica-qa/docker-compose.yml up --build -d
          echo 'Hello Test'

    - task: GitHubRelease@1
      displayName: GitHub Release
      inputs:
        gitHubConnection: 'Lucioric2000 (1)'
        repositoryName: 'Alagant/LibreClinica'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: '$(Build.BuildId)'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'


