# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://github.com/huezo

trigger:
- master

pool:
  name: Default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: DevOps
  displayName: Docker image
  jobs:
  - job: DevOps
    displayName: DevOps
#    pool:
#      vmImage: ubuntu-latest
#    pool:
#      name: Default
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: 'build'
#        Dockerfile: '**/Dockerfile'
#        tags: '$(tag)'


    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Docker DevOps
          docker build -t libreclinica:master .
          docker service rm libreclinica
          docker service create --name=libreclinica --restart-condition=any --publish=8183:8080  libreclinica:master
           docker service ps  libreclinica
          # docker rm -f libreclinica
          # docker run -d --name libreclinica -p 8183:8080 libreclinica:master
          docker ps --filter name=libreclinica

          echo 'Hello DevOps'


