trigger:
- master

pool:
  name: Libreclinica-azureVMs

resources:
  repositories:
    - repository: LcRepo
      type: github
      endpoint: Alagant
      name: Alagant/LibreClinica
      ref: refs/heads/$(Build.SourceBranchName)
    - repository: LcQA
      type: github
      endpoint: Alagant
      name: Alagant/libreclinica-qa
      ref: refs/heads/main
    - repository: LcDMM
      type: github
      endpoint: Alagant
      name: Alagant/libreclinica_drug_trial_module
      ref: refs/heads/main
    - repository: CDCOauthMockup
      type: github
      endpoint: Alagant
      name: Alagant/cdc_oauth_portal_mockup
      ref: refs/heads/main


variables:
  tag: '$(Build.BuildId)'

stages:
- stage: DevOps
  displayName: Docker image
  jobs:
  - job: DevOps
    steps:
    - checkout: LcRepo
      #clean: true
      persistCredentials: true
      fetchDepth: 1
      lfs: true
      #submodules: true
      #ref: refs/heads/lc-release-1.2.1
    - checkout: LcQA
    - checkout: LcDMM
    - checkout: CDCOauthMockup
    - task: Bash@3
      displayName: Backup the database
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p /home/azureuser/dbbackup
          cd LibreClinica/
          /usr/bin/docker compose run -e PGPASSWORD=$(PG_PASSWORD) postgres pg_dump -d libreclinica -U clinica -h postgres>/home/azureuser/dbbackup/libreclinica_$(date -Iseconds).sql
    - task: Bash@3
      displayName: Clean the docker environment
      inputs:
        targetType: 'inline'
        script: |
          cd LibreClinica/
          docker compose stop
          docker container stop $(docker container ls -aq)||echo No Docker containers to stop

    - task: Bash@3
      displayName: DevOps
      inputs:
        targetType: 'inline'
        script: |
          # Docker DevOps
          cd /home/azureuser/Alagant_projects/LibreClinica/
          git checkout $(Build.SourceBranchName)
          echo checked out branch $(Build.SourceBranchName)
          git pull
          docker compose build libreclinica
          docker compose up -d
          docker ps -a
          echo 'Hello DevOps'
          ls -ltra

    - task: Bash@3
      displayName: Test and report commit message
      inputs:
        targetType: 'inline'
        script: |
          cd libreclinica-qa/
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up libreclinica-qa
      # Change the comment text here to test a new commit. Test nov 17 2023 b.
      env:
        CONFLUENCE_USERNAME: $(CONFLUENCE_USERNAME)
        CONFLUENCE_ACCESS_TOKEN: $(CONFLUENCE_ACCESS_TOKEN)
        CONFLUENCE_SPACE_ID: $(CONFLUENCE_SPACE_ID)
        CONFLUENCE_PAGE_ID: $(CONFLUENCE_PAGE_ID)
        LC_ROOT_USERNAME: $(LC_ROOT_USERNAME)
        LC_ROOT_PASSWORD: $(LC_ROOT_PASSWORD)
        source_version: $(Build.SourceVersion)
        build_id: $(Build.BuildId)
        build_number: $(Build.BuildNumber)
        commit_message: $(Build.SourceVersionMessage)
        branch: $(Build.SourceBranchName)
