# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: Default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
#    pool:
#      vmImage: ubuntu-latest
#    pool:
#      name: Default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 'libreclinica:libreclinica'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          docker rm -f libreclinica
          docker run -d --name libreclinica -p 8183:8080 $(Build.BuildId)
          docker ps --filter name=libreclinica

          echo 'Hello world'


    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'

