services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    environment: 
      POSTGRES_PASSWORD: libreclinica
      POSTGRES_USER: libreclinica
      POSTGRES_DB: libreclinica
  libreclinica:
    build:
      context: .
      dockerfile: Dockerfile_libreclinica
    #ports:
    #  - 8484:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: libreclinica
      POSTGRES_USER: libreclinica
      POSTGRES_DB: libreclinica
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile_tomcat
    ports:
      - 8485:8080
    depends_on:
      - libreclinica
