version: '3.1'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file: .env
  adminer:
    image: adminer
    restart: always
    ports:
      - "8070:8080"

  libreclinica:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8485:8080"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - libreclinica:/libreclinica

volumes:
  libreclinica:
