version: '3.1'
services:
  postgres:
    image: postgres:14-alpine
    #build:
    #  context: docker
    #  dockerfile: Dockerfile_postgres
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8181:8080"

  libreclinica:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - libreclinica:/libreclinica

  dmm:
    build:
      context: ../libreclinica_drug_trial_module/
      dockerfile: Dockerfile
    ports:
      - "81:81"  # Map port 5000 of the host to port 5000 of the container
    volumes:
      - ../libreclinica_drug_trial_module:/app  # Mount the current directory into the container's /app directory
    environment:
      FLASK_APP: flask_app  # Set the FLASK_APP environment variable
    #command: ls -lh /app/flask_app
    command: flask run -p 81 -h dmm --no-reload

volumes:
  libreclinica:
#  postgres_data:
#    driver: local