FROM postgres:11
LABEL maintainer="Lucio M. <lucioric2000@hotmail.com>"
MAINTAINER   Lucio M. <lucioric2000@hotmail.com>
COPY postgres_setup.sh /docker-entrypoint-initdb.d/init-user-db.sh
#ENTRYPOINT psql -U postgres -c "CREATE ROLE clinica LOGIN ENCRYPTED PASSWORD 'clinica' SUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE; CREATE DATABASE libreclinica WITH ENCODING='UTF8' OWNER=clinica;"

