services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    env_file: .env
    ports:
      - 5432:5432

  libreclinica:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8485:8080
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - libreclinica:/libreclinica
volumes:
    libreclinica:
