version: '3.1'
services:
  postgres:
    image: postgres:14-alpine
    #build:
    #  context: docker
    #  dockerfile: Dockerfile_postgres
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    environment:
      -POSTGRES_PASSWORD: clinica
      -PGPASSWORD: clinica
      -POSTGRES_USER: clinica
      -POSTGRES_DB: libreclinica
      -POSTGRES_HOST: postgres
      -POSTGRES_PORT: 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - "8181:8080"

  libreclinica_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - libreclinica:/libreclinica
volumes:
  libreclinica:
