version: '3.8'
services:
  postgres:
    #image: postgres:14-alpine
    build:
      context: docker
      dockerfile: Dockerfile_postgres
    ports:
      - "5432:5432"
    restart: always
    #env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./postgres/init:/docker-entrypoint-initdb.d
      - dbbackup:/dbbackup
  adminer:
    image: adminer
    #restart: always
    ports:
      - "8181:8080"

  libreclinica:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
      - .env_emails
    volumes:
      - libreclinica_src:/libreclinica
      - libreclinica_config:/usr/local/tomcat/libreclinica.config
      - libreclinica_data:/usr/local/tomcat/libreclinica.data
      - libreclinica_webapps:/usr/local/tomcat/webapps
      - mvn_cache:/root/.m2
    environment:
      #- ADMINEMAIL
      #- MAILUSERNAME
      - MAILPASSWORD_FILE=/run/secrets/mail_password
      #- DEVELOPEREMAILS
    secrets:
      - mail_password

#  dmm:
#    build:
#      context: ../libreclinica_drug_trial_module/
#      dockerfile: Dockerfile
#    ports:
#      - "81:81"  # Map port 81 of the host to port 81 of the container
#    volumes:
#      - ../libreclinica_drug_trial_module:/app  # Mount the current directory into the container's /app directory
#    environment:
#      ADMINEMAIL: ${ADMINEMAIL}
#      FLASK_APP: flask_app  # Set the FLASK_APP environment variable
#      SQLALCHEMY_DATABASE_URI: postgresql://clinica:ready4Sprint@dmmlc.postgres.database.azure.com/dmm-dev  # Set the SQLALCHEMY_DATABASE_URI environment variable
#    command: python -mpytest
volumes:
  libreclinica_src:
    driver: local
  libreclinica_webapps:
    driver: local
  mvn_cache:
    driver: local
  libreclinica_config:
    driver: local
  libreclinica_data:
    driver: local
  pgdata:
    driver: local
  dbbackup:
    driver_opts:
      type: none
      device: ${HOME}/dbbackup
      o: bind
secrets:
  mail_password:
    environment: "MAIL_PASSWORD"
#env_file:
#  - ./.env
#  - ./.env_emails
