version: '3.1'
services:
  postgres:
    build:
      context: docker
      dockerfile: Dockerfile_postgres
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
  adminer:
    image: adminer
    restart: always
    ports:
      - "8070:8080"

  libreclinica_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - libreclinica:/libreclinica
volumes:
  libreclinica:
