version: '3.1'
services:
  postgres:
    #image: postgres:14-alpine
    build:
      context: docker
      dockerfile: Dockerfile_postgres
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    volumes:
        - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8181:8080"

  libreclinica_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - libreclinica:/libreclinica
      - libreclinica_config:/usr/local/tomcat/libreclinica.config
volumes:
  libreclinica:
  libreclinica_config:
    driver: local
  pgdata:
    driver: local
    #driver_opts:
    #  type: none
    #  device: /home/azureuser/pgdata
    #  o: bind
