FROM ubuntu:22.04
LABEL maintainer="Lucio M. <lucioric2000@hotmail.com>"
MAINTAINER   Lucio M. <lucioric2000@hotmail.com>
# Create the file repository configuration:
RUN apt-get update -y
RUN apt-get install -y wget gnupg2
RUN echo "deb https://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list

    # Import the repository signing key:
RUN  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

    # Update the package lists:
RUN apt-get update -y

    # Install the latest version of PostgreSQL.
    # If you want a specific version, use 'postgresql-12' or similar instead of 'postgresql':
#RUN apt-get -y install postgresql-11 postgresql-client-11

    # Optionally install the postgresql-doc package to get the documentation in HTML format.
    # Use 'postgresql-doc-12' for the doc of a specific version, instead of 'postgresql-doc':
#ENTRYPOINT psql -U postgres -c "\l" -U postgres
