FROM postgres:14-alpine
LABEL maintainer="Lucio M. <lucioric2000@hotmail.com>"
MAINTAINER   Lucio M. <lucioric2000@hotmail.com>
ADD libreclinica_2023-12-24T01_20_23-06_00.sql /docker-entrypoint-initdb.d/libreclinica_2023-12-24T01_20_23-06_00.sql
