FROM postgres:14-alpine
USER postgres
LABEL maintainer="Lucio M. <lucioric2000@hotmail.com>"
MAINTAINER   Lucio M. <lucioric2000@hotmail.com>
ADD ./libreclinica_backup.sql /docker-entrypoint-initdb.d/init.sql
# ADD . /docker-folder