Cypress.on('uncaught:exception', (err, runnable) => {
    return false;
});

describe('Load page', () => {
    it('Visits the LibreClinica', () => {
        cy.visit('http://localhost:8080/LibreClinica/pages/login/login')
        cy.contains('Login')
    })
    it('Login and navegate for main pages', () => {
        cy.visit('http://localhost:8080/LibreClinica/pages/login/login')
        cy.url().should('include', 'http://localhost:8080/LibreClinica/pages/login/login')
        cy.get('[id="username"]').should('exist').type('root')
        cy.get('[id="j_password"]').should('exist').type('kevin12345')
        cy.get('[name="submit"]').should('exist').click()
        cy.url().should('include', 'http://localhost:8080/LibreClinica/MainMenu')
        cy.contains('Welcome to')
        cy.contains('Change Study/Site')
        cy.contains('Log Out')
        cy.contains('Home').click()
        cy.contains('Subject Matrix').click()
        cy.contains('Notes & Discrepancies').click()
        cy.contains('Study Audit Log').click()
        cy.contains('Tasks').trigger('mouseover')
        cy.contains('Submit Data')
        cy.contains('Subject Matrix')
        cy.contains('Schedule Event')
        cy.contains('Add Subject')
        cy.contains('View Events')
        cy.contains('Notes & Discrepancies')
        cy.contains('Import Data')
        cy.contains('Monitor and Manage Data')
        cy.contains('Source Data Verification')
        cy.contains('Study Audit Log')
        cy.contains('Extract Data')
        cy.contains('View Datasets')
        cy.contains('Create Dataset')
        cy.contains('Study Setup')
        cy.contains('Users')
        cy.contains('View Study')
        cy.contains('Administration')
        cy.contains('Subjects')
        cy.contains('Jobs')
        cy.contains('Studies')
        cy.contains('Users')
        cy.contains('CRFs')
        cy.contains('Other')
        cy.contains('Log Out')
        cy.contains('Update Profile')
    })
});